### ISSUE TITLE
想问一下如果要在群聊里得到某个qq后，发送私聊信息给那个人应该怎么写

### ISSUE THREAD

**Issue by sailist** [richardchien/none-bot#19]
找到了一个send_private_msg方法，但没找到它的实现，我在on_command调用里引用了一下发现报错了
`Task exception was never retrieved
future: <Task finished coro=<handle_message() done, defined at C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\message.py:20> exception=ActionFailed() created at C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\__init__.py:39>
source_traceback: Object created at (most recent call last):
  File "C:/E/jupyter_notebook/小工具/pyQQ/test.py", line 11, in <module>
    none.run()
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\__init__.py", line 104, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\__init__.py", line 58, in run
    *args, **kwargs)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\__init__.py", line 195, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\quart\app.py", line 1337, in run
    run_single(self, config, loop=loop)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\hypercorn\run.py", line 181, in run_single
    loop.run_forever()
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1423, in _run_once
    handle._run()
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 126, in send
    return self.gen.send(value)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\__init__.py", line 39, in _
    asyncio.ensure_future(handle_message(self, ctx))
Traceback (most recent call last):
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\message.py", line 43, in handle_message
    handled = await handle_command(bot, ctx)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\command.py", line 465, in handle_command
    disable_interaction=disable_interaction)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\command.py", line 518, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\tasks.py", line 339, in wait_for
    return (yield from fut)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 126, in send
    return self.gen.send(value)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\none\command.py", line 61, in run
    await self.func(session)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "C:\E\jupyter_notebook\小工具\pyQQ\plugins\catchSpyder.py", line 140, in join
    await bot.send_private_msg(user_id=qq, message='哇')
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\api.py", line 170, in call_action
    action, **params)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\api.py", line 140, in call_action
    return _handle_api_result(await ResultStore.fetch(seq))
  File "C:\Users\Sailist\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\api.py", line 39, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed`

**Comment by sailist** [comment]
> `aiocqhttp.exceptions.ActionFailed` 表示调用到了接口，但动作失败了，可以打印 `e.retcode` 查看错误码，（如果是小于 0 的）也可以在酷 Q 日志里看到错误信息
> 
> 你这个多半是因为你想发送的目标最近没有在群里说过话，或者没 at 你

啊蟹蟹蟹蟹，我又回头看了下我写的qq获取的，发现把昵称和qq号写反了...改了后就好了Orz
然后这里附一下send_private_msg相关方法所在的文档，是在cqhttp里：
https://cqhttp.cc/docs/4.5/#/API

**Comment by richardchien** [comment]
OK，文档加上了 https://none.rclab.tk/guide/calling-cqhttp-api.html
